name: Validate Responsive Framework

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - run: npm install
        working-directory: ./emailonacid
      - name: create screenshot output folder
        run: mkdir output
      - name: validate screenshots
        run: npm run screenshots
        working-directory: ./emailonacid
        env:
          EOA_ACCOUNT_PASSWORD: ${{ secrets.EOA_ACCOUNT_PASSWORD }}
          EOA_API_KEY: ${{ vars.EOA_API_KEY }}
      - name: publish screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: output
