name: Validate Responsive Framework

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - run: npm install
        working-directory: ./emailonacid
      - run: npm run screenshots
        working-directory: ./emailonacid
        env:
          EOA_ACCOUNT_PASSWORD: ${{ secrets.EOA_ACCOUNT_PASSWORD }}
          EOA_API_KEY: ${{ secrets.EOA_API_KEY }}
