name: Validate Pull Request

on:
  pull_request:

jobs:
  publish:
    name: Publish latest.html
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 📄 Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: 📦 Publish latest.html as artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-html
          path: source/latest.html
      - name: 📦 Publish baseline screenshots as artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline-screenshots
          path: output/*.png
